services:
  mysql-product:
    image: mysql:8.0
    container_name: mysql-product
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: product_db
    ports:
      - "3308:3306"
    volumes:
      - mysql-product-data:/var/lib/mysql

volumes:
  mysql-product-data: